name: SamSkyBridge
main: com.signition.samskybridge.Main
version: 1.1.3
api-version: 1.16
author: minkang+chatgpt
commands:
  island:
    description: Island main command
    aliases: [섬]
    usage: /섬 <레벨|업그레이드>
