name: SamSkyBridge
main: com.signition.samskybridge.Main
version: 1.3.4
api-version: 1.16

commands:
  samsky:
    description: Main SamSkyBridge command
    aliases: [섬, is, island]

  섬:
    description: Korean alias for SamSkyBridge

  samskyreload:
    description: reload SamSkyBridge configs
    permission: samsky.reload
