name: SamSkyBridge
main: com.signition.samskybridge.Main
version: 1.2.0
api-version: 1.13

commands:
  samsky:
    description: Main SamSkyBridge command
    aliases: [섬, is, island]
    permission: samsky.use

  섬:
    description: Korean alias for SamSkyBridge
    permission: samsky.use

  samskyreload:
    description: reload SamSkyBridge configs
    permission: samsky.reload
