name: SamSkyBridge-IslandOnly
main: com.signition.samskybridge.Main
version: 1.0.21-island-v12
api-version: 1.0.21-island-v12
softdepend: [Vault, BentoBox, BSkyBlock]
commands:
  섬:
    description: Island main command
    usage: /섬
permissions:
  samskybridge.admin:
    default: op
