name: UltimateRPS
main: com.minkang.ultimate.rps.UltimateRpsPlugin
version: 1.6.18
api-version: "1.16"
author: minkang
commands:
  rps:
    description: 가위바위보 시스템
    usage: /rps
    aliases: [가위바위보]
permissions:
  ultimaterps.use:
    default: true
  ultimaterps.admin:
    default: op
