name: SkyblockdXP
main: com.signition.samskybridge.Main
version: 1.1.0-island-v1
api-version: 1.16
author: minkang
commands:
  xpreload:
    description: Reload SkyblockdXP config
    usage: /xpreload
  xpx:
    description: Show your current custom XP stats
    usage: /xpx
