

name: SamSkyBridge
main: com.signition.samskybridge.Main
version: 0.8.0
api-version: 1.16
author: signition
softdepend: [Vault, BentoBox]
commands:
  섬:
    description: 섬 관련 명령어
    usage: /섬
    aliases: [island, sky, sk]
