name: SamSkyBridge
main: com.signition.samskybridge.Main
version: 0.13.40
api-version: 1.16
author: signition
softdepend: [Vault, BentoBox, BSkyBlock, PlaceholderAPI]
commands:
  섬:
    description: 섬 관련 명령어
    aliases: [sky, island]
    usage: |
      /섬
      /섬 설치 <광산|농장>
      /섬 제거 <광산|농장>
      /섬 업그레이드
      /섬 랭킹
      /섬 매물
      /섬 매물 등록 <가격>
      /섬 채팅
      /섬 설정 리로드
