name: SkyblockdXP
main: com.signition.samskybridge.Main
version: 1.0.33-island-v5
api-version: 1.0.33-island-v5
author: minkang
commands:
  xpreload:
    description: Reload SkyblockdXP config
    usage: /xpreload
  xpx:
    description: Show your current custom XP stats
    usage: /xpx
