name: SamSkyBridge-IslandOnly
main: com.signition.samskybridge.Main
version: 1.0.26-island-v17+ci28
api-version: 1.16
author: signition
softdepend: [BentoBox, LuckPerms, PlaceholderAPI, Vault]
commands:
  섬:
    description: 섬 명령어
    usage: /섬 리로드
    aliases: [island, sb]
