
name: SamSkyBridge-KR
main: com.signition.samskybridge.Main
version: 1.0.5
api-version: 1.16
author: signition
softdepend: [Vault, BentoBox]
commands:
  섬:
    description: 섬 관련 명령어 (한국어 별칭 → /is 전달)
    usage: /섬
    aliases: [sky, sk]
