name: SamSkyBridge-KR
main: com.minkang.usp2.Main
version: 1.0.7
api-version: 1.16
author: MinGang
softdepend: [Vault, Essentials, Citizens]
commands:
  배틀종료:
    description: Pixelmon endbattle
    permission: usp.battle

  돈:
    description: 잔액/송금/순위
    permission: usp.money

  수표:
    description: 수표 발급(소지금 차감, 무권한)

  수리권:
    description: 수리권 발급
    permission: usp.repair.give

  상점:
    description: 상점 열기/관리/연동

  거래:
    description: 거래 요청/수락/거절

  잠금:
    description: 잠금 시간|영구|추가|목록|해제

  잠금권:
    description: 잠금권 발급(영구/시간)
    permission: usp.lock.give

  야투:
    description: 야간투시 토글(무권한)

  상점리로드:
    description: 상점/설정 리로드
